# generated by rails g pundit:install
class ApplicationPolicy
  attr_reader :user, :record

  def initialize(user, record)
    @user = user
    @record = record
  end

  def index?
    true
  end

  def show?
    scope.where(id: record.id).exists?
  end

  def create?
    user.present?
  end

  def new?
    create?
  end

  def update?
    (user.present? && record.user == user) || (user.present? && user.role?(:admin))
  end

  def edit?
    update?
  end

  def destroy?
    (user.present? && record.user == user) || (user.present? && user.role?(:admin))
  end

  def scope
    Pundit.policy_scope!(user, record.class)
  end

  self::Scope = Struct.new(:user, :scope) do
    def resolve
      scope
    end
  end
end

